// domain
export const DOMAIN = "https://c43658a3a90b.ngrok.io";
// export const DOMAIN = "https://f32531d8ff9a.ngrok.io";
export const LIMIT = 5;

// HTTP method 
export const HTTP_READ = "GET"
export const HTTP_CREATE = "POST"
export const HTTP_UPDATE = "PUT"
export const HTTP_DELETE = "DELETE"

// HTTP headers
export const HTTP_HEADER_JSON = {"Content-Type": "Application/json"}

// types of actions
export const GET_ITEM_SUCCESS=" GET_ITEM_SUCCESS"
export const GET_ITEM_FAILURE=" GET_ITEM_FAILURE"
export const GET_ITEM_RESQUET=" GET_ITEM_RESQUET"


export const ADD_ITEM_SUCCESS=" ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAILURE=" ADD_ITEM_FAILURE"
export const ADD_ITEM_RESQUET=" ADD_ITEM_RESQUET"


export const DELETE_ITEM_SUCCESS=" DELETE_ITEM_SUCCESS"
export const DELETE_ITEM_FAILURE=" DELETE_ITEM_FAILURE"
export const DELETE_ITEM_RESQUET=" DELETE_ITEM_RESQUET"


export const UPDATE_ITEM_SUCCESS=" UPDATE_ITEM_SUCCESS"
export const UPDATE_ITEM_FAILURE=" UPDATE_ITEM_FAILURE"
export const UPDATE_ITEM_RESQUET=" UPDATE_ITEM_RESQUET"


export const PAGINATION_ITEM_SUCCESS="PAGINATION_ITEM_SUCCESS"
export const PAGINATION_ITEM_FAILURE="PAGINATION_ITEM_FAILURE"
export const PAGINATION_ITEM_RESQUET="PAGINATION_ITEM_RESQUET"


export const SEARCHPAGINATION_ITEM_SUCCESS=" SEARCHPAGINATION_ITEM_SUCCESS"
export const SEARCHPAGINATION_ITEM_FAILURE=" SEARCHPAGINATION_ITEM_FAILURE"
export const SEARCHPAGINATION_ITEM_RESQUET=" SEARCHPAGINATION_ITEM_RESQUET"
